version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../storage/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow:
    build:
      context: ..
      dockerfile: ../v2_distributed/docker/infra.Dockerfile
    container_name: airflow
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - ../../../airflow/dags:/opt/airflow/dags
      - ../../../airflow/logs:/opt/airflow/logs
      - ../../../airflow/plugins:/opt/airflow/plugins
      - ../../../versions:/opt/versions

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    command: bash -c "airflow db migrate && airflow scheduler & airflow api-server"
    
volumes:
  rabbitmq_data:
  redis_data:
  postgres_data:
  mongo_data: