services:

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ../.env
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  redis:
    image: redis:7
    env_file:
      - ../.env
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    env_file:
      - ../.env
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../storage/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mongo:
    image: mongo:6
    env_file:
      - ../.env
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow:
    build:
      context: ..
      dockerfile: ../v2_distributed/docker/infra.Dockerfile
    env_file:
      - ../.env
    container_name: airflow
    depends_on:
      - redis
      - rabbitmq
      - postgres
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - ../../../airflow/dags:/opt/airflow/dags
      - ../../../airflow/logs:/opt/airflow/logs
      - ../../../airflow/plugins:/opt/airflow/plugins
      - ../../../airflow/simple_auth_manager_passwords.json.generated:/opt/airflow/simple_auth_manager_passwords.json.generated
      - ../../../versions:/opt/versions
      - ../../../versions/v2_distributed/pipelines:/opt/airflow/dags/v2

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    command: "standalone"

volumes:
  rabbitmq_data:
  redis_data:
  postgres_data:
  mongo_data: